//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Security.Cryptography;

namespace IconicsArena.Context
{
    using System;
    using System.Collections.Generic;

    public partial class Slot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slot()
        {
            this.Bookings = new HashSet<Booking>();
        }

        public int SlotId { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> IsAvailable { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
    public static class TimeSlots
    {
        public const string Slot1 = "8.00am-10.00am";
        public const string Slot2 = "11.00am-1.00pm";
        public const string Slot3 = "2.00pm-4.00pm";
        public const string Slot4 = "5.00pm-7.00pm";
        public const string Slot5 = "8.00pm-10.00pm";
        public const string Slot6 = "11.00pm-1.00am";
    }
    public static class Price
    {
        public const string Price1 = "1500";
        public const string Price2 = "2000";
        public const string Price3 = "3000";
        public const string Price4 = "4000";
    }

    public enum Days
    {
        Sunday,
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday,
        Saturday,
    }

}
